//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientPortal.DataAccess.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailSetting
    {
        public byte Id { get; set; }
        public string Email { get; set; }
        public string Host { get; set; }
        public decimal Port { get; set; }
        public bool IsSSL { get; set; }
    }
}
