CREATE PROCEDURE [dbo].[usp_spa_Advertise]
	@Id TINYINT
AS BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ COMMITTED

	BEGIN TRY
		IF @Id > 0
			SELECT * FROM [dbo].[Advertise]
			WHERE [Id] = @Id
		ELSE
			SELECT	* 
			FROM [dbo].[Advertise]
			WHERE	EndDate >= GETDATE()
			ORDER BY [Id]
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT <> 0 
		BEGIN
			RETURN NULL
		END
	END CATCH
END