CREATE PROCEDURE [dbo].[usp_User_FindByEmail]
	@email NVARCHAR(256) = ''
AS 
BEGIN
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ COMMITTED
	BEGIN TRY
		SELECT Id FROM [dbo].[Users]
		WHERE Email = @email
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT <> 0
		BEGIN
			RETURN NULL
		END
	END CATCH
END
