//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientPortal.DataAccess.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowNavigation
    {
        public short WorkflowStateId { get; set; }
        public short NextWorkflowStateId { get; set; }
        public bool IsUsed { get; set; }
    
        public virtual WorkflowState WorkflowState { get; set; }
        public virtual WorkflowState WorkflowState1 { get; set; }
    }
}
