//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientPortal.DataAccess.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostSEO
    {
        public int PostId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Canonical { get; set; }
        public string BreadcrumbsTitle { get; set; }
        public byte MetaRobotIndex { get; set; }
        public byte MetaRobotFollow { get; set; }
        public byte MetaRobotAdvanced { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
