//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientPortal.DataAccess.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Time { get; set; }
        public string Medicine { get; set; }
        public int PhysicianId { get; set; }
        public int PatientId { get; set; }
        public string Symptom { get; set; }
        public string CreatedDate { get; set; }
        public string ModifiedDate { get; set; }
        public byte Status { get; set; }
    }
}
