//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientPortal.DataAccess.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleComment
    {
        public short Id { get; set; }
        public int ArticleId { get; set; }
        public System.DateTime Date { get; set; }
        public string Detail { get; set; }
        public int CreatedUser { get; set; }
        public byte Status { get; set; }
    
        public virtual Article Article { get; set; }
    }
}
