//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientPortal.DataAccess.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageRecipient
    {
        public int MessageId { get; set; }
        public int ReceiverId { get; set; }
        public bool IsUsed { get; set; }
    
        public virtual Message Message { get; set; }
        public virtual User User { get; set; }
    }
}
