//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientPortal.DataAccess.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HospitalCMSEntities : DbContext
    {
        public HospitalCMSEntities()
            : base("name=HospitalCMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<PostSEO> PostSEOs { get; set; }
        public virtual DbSet<PostStateHistory> PostStateHistories { get; set; }
        public virtual DbSet<PostTran> PostTrans { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Workflow> Workflows { get; set; }
        public virtual DbSet<WorkflowNavigation> WorkflowNavigations { get; set; }
        public virtual DbSet<WorkflowState> WorkflowStates { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
    }
}
