//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientPortal.DataAccess.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostStateHistory
    {
        public int Id { get; set; }
        public int PostId { get; set; }
        public byte WorkflowStateId { get; set; }
        public int UserId { get; set; }
        public string Note { get; set; }
        public string CreatedDate { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
