//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientPortal.DataAccess.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Post()
        {
            this.PostStateHistories = new HashSet<PostStateHistory>();
            this.PostTrans = new HashSet<PostTran>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Image { get; set; }
        public string Author { get; set; }
        public short WorkflowStateId { get; set; }
        public byte CategoryId { get; set; }
        public byte Status { get; set; }
        public string CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public string ModifiedDate { get; set; }
        public int MdifiedBy { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual WorkflowState WorkflowState { get; set; }
        public virtual PostSEO PostSEO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostStateHistory> PostStateHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostTran> PostTrans { get; set; }
    }
}
